### ISSUE TITLE
Traceback using script to export templates to JSON file

### ISSUE THREAD

**Issue by jrpell** [cisco-en-programmability/dnacentersdk#10]
I'm using a script from Github built to backup templates from DNA Center and it's giving a traceback error on a script in the dnacentersdk library.  Not sure what I need to do to fix it but wanted to report this.  Here's the script from Github I'm trying to run:

https://github.com/CiscoDevNet/DNAC-TemplateTool

Here's the error I'm getting:
Traceback (most recent call last):
  File "template_archive.py", line 201, in <module>
    archive_templates(dnac)
  File "template_archive.py", line 57, in archive_templates
    templates = dnac.template_programmer.gets_the_templates_available()
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\site-packages\dnacentersdk\api\v1_3_0\template_programmer.py", line 275, in gets_the_templates_available
    json=_payload)
  File "C:\Users\me\AppData\Local\Programs\Python\Python37-32\lib\site-packages\dnacentersdk\restsession.py", line 390, in get
    with self.request('GET', url, erc, 0, params=params, **kwargs) as resp:
AttributeError: __enter__

I assume it's an issue with the library cause that's where it's failing but maybe it's the script I'm running.  I just can't get past this issue.  Thanks.

**Comment by jbogarin** [comment]
@jrpell  We'll try to replicate this because the error is not clear enough.

**Comment by wastorga** [comment]
@jrpell 

Sorry for the delay.

You seem to be using a `DNA_CENTER_VERSION` below `1.3.1` since you are using `template_programmer`. 
FYI, since `1.3.1` now the module is `configuration_templates`.

Which version of the dnacentersdk are you using?

Newer versions have solved the issue with the `json=_payload`.

So I will recommend updating the dnacentersdk, if you still encounter an issue with the newer versions let me know.

**Comment by jrpell** [comment]
Oh wow. Forgot I submitted this. I've since upgraded everything and using updated versions of the SDK and all is good. Thanks!
